---
title: "storytelling pdad"
output: html_document
date: "2024-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,message = FALSE)
library(tidyverse)
library(caret)
library(rattle)
library(readxl)
library(patchwork)
library(colorspace)

PDAD_2021_Moradores <- read_delim("PDAD_2021-Moradores.csv", 
                                  delim = ";", escape_double = FALSE, locale = locale(decimal_mark = ",", 
                                                                                      grouping_mark = "."), trim_ws = TRUE)

PDAD_2021_Moradores <- janitor::clean_names(PDAD_2021_Moradores)

nomes_regioes_administrativas <- read_excel("dicionario_de_variaveis_pdad_2021.xlsx", 
                                                sheet = "anexo_1")

nomes_regioes_administrativas <-
  nomes_regioes_administrativas %>%
  janitor::clean_names() %>%
  select(valor, descricao_do_valor) %>%
  rename(a01ra = valor,
         nome_regiao_administrativa = descricao_do_valor)

nomes_destinos <- read_excel("dicionario_de_variaveis_pdad_2021.xlsx", 
                                            sheet = "anexo_12")

nomes_destinos <-
  nomes_destinos %>%
  janitor::clean_names() %>%
  select(valor, descricao_do_valor) %>%
  rename(i08 = valor,
         nome_destino = descricao_do_valor)


  

tempos_trabalho<-  
  read_excel("dicionario_de_variaveis_pdad_2021.xlsx", 
                                                sheet = "moradores", skip = 534,n_max =11, col_names = FALSE) %>%
  select(3,4) 

names(tempos_trabalho)<- c("i10","tempo_deslocamento")

meios_transporte<-
  read_excel("dicionario_de_variaveis_pdad_2021.xlsx", 
                                                sheet = "moradores", skip = 525,n_max = 9, col_names = FALSE) %>%
  select(3,4) 

names(meios_transporte)<- c("i09_8","meio_transporte")  

  



```


```{r cars}
#Gráfico da distribuição dos tempos para o trabalho

peso_total_valido<- 
  (PDAD_2021_Moradores %>%
  filter(!i10%in% c("88888","99999")) %>%
  summarise(pop_total = sum(peso_mor)))$pop_total

PDAD_2021_Moradores%>%
  filter(!i10%in% c("88888","99999")) %>%
  summarise(proporcao_valido = ((round(sum(peso_mor),0))/peso_total_valido)*100,
            .by = i10) %>%
  inner_join(tempos_trabalho) %>%
  arrange(i10) %>%
  mutate(tempo_deslocamento = reorder(tempo_deslocamento, desc(i10)),
         proporcao_valido = round(proporcao_valido,1)) %>%
  ggplot(aes(x=proporcao_valido, y=tempo_deslocamento)) +
  geom_col()+
  geom_text(aes(label=paste0(proporcao_valido,"%")),
            hjust = c(rep(1,5),rep(-0.1,4)), color = c(rep("white",5),rep("black",4)))+
  theme_light()+
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Referência: 2021",
    caption = "Fonte: IPE-DF. Elaboração própria",
    x="",
    y=""
  )
  

```




```{r, fig.width=8, fig.height=5}


PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, mesma_regiao)) %>%
  ggplot(aes(y=mesma_regiao, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color="black", position = "dodge") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Referência: 2021",
    caption = "Fonte: IPE-DF. Elaboração própria",
    x="Proporção do total deslocamentos (%)",
    y="Mesma região",
    fill = "Tempo de deslocamento"
  )


  
```


```{r}
#Deslocamentos na mesma região e tipos de deslocamentos


peso_total_valido_mesma_regiao<- 
  (PDAD_2021_Moradores %>%
     filter(!i10%in% c("88888","99999")) %>%
     mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
     filter(mesma_regiao == "sim") %>%
     summarise(pop_total = sum(peso_mor)))$pop_total

PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, meio_transporte, mesma_regiao)) %>%
  mutate(meio_transporte = ifelse(meio_transporte == "Transporte Privado (empresa de aplicativo, táxi, fornecido pela empresa)", 
                                  "Transporte Privado", 
                                  meio_transporte)) %>%
  mutate(meio_transporte = fct_reorder(meio_transporte, proporcao, sum)) %>%
  ggplot(aes(y=meio_transporte, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Meios de transporte/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%) ",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)




```

```{r fig.width=10}
#Deslocamentos na mesma região e regiões administrativas


PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  #filter(mesma_regiao == "sim") %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(nomes_regioes_administrativas) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, nome_regiao_administrativa, mesma_regiao)) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, proporcao, sum)) %>%
  ggplot(aes(y=nome_regiao_administrativa, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Regiões administrativas/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)



```

```{r}
#Tempos de deslocamento e renda


PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08|i08==0 ,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  filter(!(i20 %in% c(77777, 88888, 99999) )) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  summarise( media_podenderada = weighted.mean(i20, na.rm = TRUE),
             .by = c( tempos_deslocamento)) %>%
  arrange(desc(media_podenderada)) %>%
    ggplot(aes(y=tempos_deslocamento, x=media_podenderada)) +
  geom_col(aes(fill= tempos_deslocamento), position = "dodge", color = "black", show.legend = FALSE) + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Análise por renda",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x= "Média ponderada da última remuneração em (R$)",
    y= "",
    fill = "Tempo de deslocamento"
  ) 



```

```{r}

PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  #filter(mesma_regiao == "sim") %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  filter(i09_8 == 7) %>%
  inner_join(nomes_regioes_administrativas) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, nome_regiao_administrativa, mesma_regiao)) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, proporcao, sum)) %>%
  ggplot(aes(y=nome_regiao_administrativa, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: a pé",
    subtitle = "Regiões administrativas/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)


```

```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  filter(i09_8 %in% c(2)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c( tempos_deslocamento, nome_regiao_administrativa, mesma_regiao)) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, proporcao, sum)) %>%
  ggplot(aes(y=nome_regiao_administrativa, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color= "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: automóvel",
    subtitle = "Regiões administrativas/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)

```



```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  filter(i09_8 %in% c(1)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c( tempos_deslocamento, nome_regiao_administrativa, mesma_regiao)) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, proporcao, sum)) %>%
  ggplot(aes(y=nome_regiao_administrativa, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color= "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: ônibus",
    subtitle = "Regiões administrativas/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)

```


```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  mutate(meio_transporte = ifelse(meio_transporte == "Transporte Privado (empresa de aplicativo, táxi, fornecido pela empresa)", 
                                  "Transporte Privado", 
                                  meio_transporte)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  filter(a01ra == 22) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, meio_transporte, mesma_regiao)) %>%
  mutate(meio_transporte = fct_reorder(meio_transporte, proporcao, sum)) %>%
  ggplot(aes(y=meio_transporte, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Sudoeste e Octogonal",
    subtitle = "Meio de transporte/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)
```

```{r fig.width=8}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(nomes_destinos) %>%
  filter(a01ra == 22) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, nome_destino, mesma_regiao)) %>%
  mutate(nome_destino = fct_reorder(nome_destino, proporcao, sum)) %>%
  ggplot(aes(y=nome_destino, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Sudoeste e Octogonal",
    subtitle = "Destinos",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) 

```



```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  mutate(meio_transporte = ifelse(meio_transporte == "Transporte Privado (empresa de aplicativo, táxi, fornecido pela empresa)", 
                                  "Transporte Privado", 
                                  meio_transporte)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  filter(a01ra == 1) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, meio_transporte, mesma_regiao)) %>%
  mutate(meio_transporte = fct_reorder(meio_transporte, proporcao, sum)) %>%
  ggplot(aes(y=meio_transporte, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Plano Piloto",
    subtitle = "Meio de transporte/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)
```


```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  mutate(meio_transporte = ifelse(meio_transporte == "Transporte Privado (empresa de aplicativo, táxi, fornecido pela empresa)", 
                                  "Transporte Privado", 
                                  meio_transporte)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  filter(a01ra == 9) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, meio_transporte, mesma_regiao)) %>%
  mutate(meio_transporte = fct_reorder(meio_transporte, proporcao, sum)) %>%
  ggplot(aes(y=meio_transporte, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Ceilândia",
    subtitle = "Meio de transporte/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)
```

```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(nomes_destinos) %>%
  filter(a01ra == 9) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, nome_destino, mesma_regiao)) %>%
  mutate(nome_destino = fct_reorder(nome_destino, proporcao, sum)) %>%
  ggplot(aes(y=nome_destino, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color= "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Ceilândia",
    subtitle = "Destinos",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) 
```



```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(meios_transporte) %>%
  mutate(meio_transporte = ifelse(meio_transporte == "Transporte Privado (empresa de aplicativo, táxi, fornecido pela empresa)", 
                                  "Transporte Privado", 
                                  meio_transporte)) %>%
  inner_join(nomes_regioes_administrativas) %>%
  filter(a01ra == 4) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, meio_transporte, mesma_regiao)) %>%
  mutate(meio_transporte = fct_reorder(meio_transporte, proporcao, sum)) %>%
  ggplot(aes(y=meio_transporte, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color = "black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Brazlândia",
    subtitle = "Meio de transporte/mesma região (s/n)",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) +
  facet_wrap(mesma_regiao~.)
```

```{r}
PDAD_2021_Moradores %>%
  mutate(mesma_regiao = ifelse(a01ra==i08,"sim","não")) %>%
  filter(!i10%in%c(88888,99999)) %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  inner_join(nomes_destinos) %>%
  filter(a01ra == 4) %>%
  summarise(proporcao = round((sum(peso_mor)/peso_total_valido)*100,1)  ,
            .by = c(tempos_deslocamento, nome_destino, mesma_regiao)) %>%
  mutate(nome_destino = fct_reorder(nome_destino, proporcao, sum)) %>%
  ggplot(aes(y=nome_destino, x=proporcao)) +
  geom_col(aes(fill= tempos_deslocamento), color="black") + 
  scale_fill_discrete_qualitative(palette="Dark 3")+
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF: Brazlândia",
    subtitle = "Destinos",
    caption = "Fonte: IPE-DF. Dados de 2021. Elaboração própria",
    x="Proporção do total de deslocamentos (%)",
    y="",
    fill = "Tempo de deslocamento"
  ) 
```


```{r fig.height=8}
#Gráfico da distribuição dos tempos para o trabalho por região administrativa



peso_area_valido<- 
  PDAD_2021_Moradores %>%
  filter(!i10%in% c("88888","99999")) %>%
  summarise(pop_area_valido = sum(peso_mor),
            .by = a01ra)

dados_grafico_1<-
PDAD_2021_Moradores%>%
  filter(!i10%in% c("88888","99999")) %>%
  inner_join(nomes_regioes_administrativas) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, peso_mor,sum)) %>%
  summarise(soma_valido = round(sum(peso_mor),0),
            .by = c(i10,nome_regiao_administrativa,a01ra )) %>%
  ungroup() %>%
  inner_join(peso_area_valido) %>%
  summarise(proporcao_valido = (soma_valido/pop_area_valido)*100,
            .by = c(i10,nome_regiao_administrativa )) %>%
  ungroup() %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  mutate(proporcao_valido = round(proporcao_valido,1)) %>%
  summarise(proporcao_valido = sum(proporcao_valido),
            .by= c(tempos_deslocamento, nome_regiao_administrativa)) %>%
  ungroup() %>%
  arrange(nome_regiao_administrativa)






dados_grafico_2<-
PDAD_2021_Moradores%>%
  filter(!i10%in% c("88888","99999")) %>%
  inner_join(nomes_regioes_administrativas) %>%
  mutate(nome_regiao_administrativa = fct_reorder(nome_regiao_administrativa, peso_mor,sum)) %>%
  summarise(soma_valido = round(sum(peso_mor),0),
            .by = c(i10,nome_regiao_administrativa,a01ra )) %>%
  ungroup() %>%
  summarise(proporcao_valido = (soma_valido/peso_total_valido)*100,
            .by = c(i10,nome_regiao_administrativa )) %>%
  ungroup() %>%
  mutate(tempos_deslocamento = ifelse(i10<=2,"Até 30 minutos","Acima de 30 minutos")) %>%
  mutate(proporcao_valido = round(proporcao_valido,1)) %>%
  summarise(proporcao_valido = sum(proporcao_valido),
            .by= c(tempos_deslocamento, nome_regiao_administrativa)) %>%
  ungroup() %>%
  arrange(nome_regiao_administrativa)


graf1<-
dados_grafico_1 %>% 
  ggplot(aes(x=proporcao_valido, y=nome_regiao_administrativa)) +
  geom_col(aes(fill=tempos_deslocamento), position = "fill")+
  geom_vline(xintercept = 0.5, linetype = "dashed") +
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Referência: 2021",
    caption = "Fonte: IPE-DF. Elaboração própria",
    x="",
    y=""
  ) 

graf2<-
dados_grafico_2 %>% 
  ggplot(aes(x=proporcao_valido, y=nome_regiao_administrativa)) +
  geom_col(aes(fill=tempos_deslocamento))+
  #geom_vline(xintercept = 0.5, linetype = "dashed") +
  theme_light()+
  theme(panel.grid = element_blank()) +
  labs(
    title = "Tempos de deslocamento para trabalho no DF",
    subtitle = "Referência: 2021",
    caption = "Fonte: IPE-DF. Elaboração própria",
    x="",
    y=""
  ) 

graf1/graf2

            
```


